
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author j.mcclure
 */
public class votingPage1 extends javax.swing.JFrame {

    //global variables
    Connection connection;
    Statement state; //insert 
    
    ResultSet rs = null; //select
    PreparedStatement ps = null; //select
    
    int instagateDebate;
    
    int chairID;
    int delegateID;
    int committeeID; 
    int countryID;
  
    public void setChairID(int chairID){
         this.chairID = chairID;
    }
    
    public void setCommitteeID(int committeeID){
        this.committeeID = committeeID;
    }
    
    public void setCombobox(){
        
        try{
            
            //get country names and add to drop down list
            String country = "SELECT `countryName`, country.`countryID`, `committeeID` FROM `country`, `delegate` WHERE country.countryID =delegate.countryID AND `committeeID`= "+committeeID+"";
            ps = connection.prepareStatement(country);
            rs = ps.executeQuery();

            while (rs.next()) {
               jComboBox1.addItem(rs.getString("countryName"));
            }
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public votingPage1(){
        
        //create connection
        //connect to database
        connectToDatabase Test = new connectToDatabase();
        Test.connectToDatabase();
        //update connection variable
        connection = Test.getConnectionVariable(connection);

        //put interface in place
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSliderHumour = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jSliderQuality = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jSliderPOI = new javax.swing.JSlider();
        jRadioButtonInstagate = new javax.swing.JRadioButton();
        submit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonAwards = new javax.swing.JButton();
        jButton_logOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Country of Delegate");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Quality of Speech");

        jSliderHumour.setMajorTickSpacing(1);
        jSliderHumour.setMaximum(5);
        jSliderHumour.setMinimum(1);
        jSliderHumour.setPaintLabels(true);
        jSliderHumour.setPaintTicks(true);
        jSliderHumour.setSnapToTicks(true);
        jSliderHumour.setValue(3);

        jLabel3.setText("Humour in Speech");

        jSliderQuality.setMajorTickSpacing(1);
        jSliderQuality.setMaximum(5);
        jSliderQuality.setMinimum(1);
        jSliderQuality.setPaintLabels(true);
        jSliderQuality.setPaintTicks(true);
        jSliderQuality.setSnapToTicks(true);
        jSliderQuality.setValue(3);

        jLabel4.setText("Ability to Handle Poins of Information");

        jSliderPOI.setMajorTickSpacing(1);
        jSliderPOI.setMaximum(5);
        jSliderPOI.setMinimum(1);
        jSliderPOI.setPaintLabels(true);
        jSliderPOI.setPaintTicks(true);
        jSliderPOI.setSnapToTicks(true);
        jSliderPOI.setToolTipText("");
        jSliderPOI.setValue(3);

        jRadioButtonInstagate.setText("Added New Information to Debate");
        jRadioButtonInstagate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonInstagateActionPerformed(evt);
            }
        });

        submit.setText("Submit Vote");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jButton1.setText("Timer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonAwards.setText("Awards Page");
        jButtonAwards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAwardsActionPerformed(evt);
            }
        });

        jButton_logOut.setText("Sign Out");
        jButton_logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(186, 186, 186)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderQuality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(submit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_logOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonAwards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderHumour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSliderPOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jRadioButtonInstagate))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jSliderQuality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jSliderHumour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jSliderPOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)))
                .addGap(33, 33, 33)
                .addComponent(jButton_logOut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(jButtonAwards))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonInstagate)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        
    //get values for slider qualities
        int qualityOfSpeech = jSliderQuality.getValue();
        int humour = jSliderHumour.getValue();
        int poi = jSliderPOI.getValue();
        String country = jComboBox1.getSelectedItem().toString();
    
    try{
        
        //countryName to countryID
        String quereyCountry = "SELECT `countryID` FROM `country` WHERE `countryName`= ?";
        ps = connection.prepareStatement(quereyCountry);
        ps.setString(1, country);
        rs = ps.executeQuery();

        while (rs.next()) {
            countryID = rs.getInt("countryID");
        }
        
        //get delegateID
        String quereydelegate = "SELECT `delegateID` FROM `delegate` WHERE `countryID`= " + countryID+ " AND `committeeID`="+committeeID+""; //need to fix
        ps = connection.prepareStatement(quereydelegate);
        rs = ps.executeQuery();

        while (rs.next()) {
            delegateID = rs.getInt("delegateID");
        }
    }catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
    }
    
    
   try{
        Statement state=(Statement)connection.createStatement();
        String sql_insertVotingRecord = "INSERT INTO `voting` VALUES("+delegateID+","+committeeID +","+chairID+","+qualityOfSpeech+","+humour+","+poi+","+instagateDebate+")";
        state.executeUpdate(sql_insertVotingRecord);
        
        JOptionPane.showMessageDialog(null,"Your vote has been processed");
        //default all voting slides
        jSliderQuality.setValue(3);
        jSliderHumour.setValue(3);
        jSliderPOI.setValue(3);
        jComboBox1.setSelectedItem(0);
        jRadioButtonInstagate.setSelected(false);
        
        

    } catch (Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage() ,"Error cannot insert voting record", 1);
    }

    
    
        
    //scores get inputted into database into voting table

    
    }//GEN-LAST:event_submitActionPerformed

    private void jRadioButtonInstagateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonInstagateActionPerformed
        instagateDebate = 2;
    }//GEN-LAST:event_jRadioButtonInstagateActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false); //get rid of the current form
        UNTimer form = new UNTimer();
    
        form.setCommitteeID(committeeID);
        form.setChairID(chairID);
        form.setCombobox();
        
        form.setVisible(true); //display timer page
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAwardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAwardsActionPerformed
        this.setVisible(false);
        
        AwardsCommittee form = new AwardsCommittee();
        form.setVisible(true);
        form.setCommitteeID(committeeID);
        form.setChairID(chairID);
        form.ranking();
    }//GEN-LAST:event_jButtonAwardsActionPerformed

    private void jButton_logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logOutActionPerformed
        
        this.setVisible(false);
        
        homePage form = new homePage();
        form.setVisible(true);
        
    }//GEN-LAST:event_jButton_logOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(votingPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(votingPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(votingPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(votingPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
    
                    new votingPage1().setVisible(true);
                    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAwards;
    private javax.swing.JButton jButton_logOut;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonInstagate;
    private javax.swing.JSlider jSliderHumour;
    private javax.swing.JSlider jSliderPOI;
    private javax.swing.JSlider jSliderQuality;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
